//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fashionshopEntities : DbContext
    {
        public fashionshopEntities()
            : base("name=fashionshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banner> banners { get; set; }
        public virtual DbSet<infomationAccount> infomationAccounts { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<productSize> productSizes { get; set; }
        public virtual DbSet<subImage> subImages { get; set; }
        public virtual DbSet<formpage> formpages { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<categoryFrist> categoryFrists { get; set; }
        public virtual DbSet<categorySecond> categorySeconds { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<account> accounts { get; set; }
    }
}
